data_dir: D:\kaggle-child-mind-institute-detect-sleep-states\data
processed_dir: D:\kaggle-child-mind-institute-detect-sleep-states\processed_data
output_dir: D:\kaggle-child-mind-institute-detect-sleep-states\output
model_dir: D:\kaggle-child-mind-institute-detect-sleep-states\output\train
sub_dir: .\